return {
  -- {
  --   'rcarriga/nvim-notify',
  --   keys = {
  --     {
  --       '<leader>un',
  --       function()
  --         require('notify').dismiss { silent = true, pending = true }
  --       end,
  --       desc = 'Dismiss All Notifications',
  --     },
  --   },
  --   opts = {
  --     stages = 'static',
  --     timeout = 3000,
  --     max_height = function()
  --       return math.floor(vim.o.lines * 0.75)
  --     end,
  --     max_width = function()
  --       return math.floor(vim.o.columns * 0.75)
  --     end,
  --     on_open = function(win)
  --       vim.api.nvim_win_set_config(win, { zindex = 100 })
  --     end,
  --   },
  --   init = function()
  --     -- when noice is not enabled, install notify on VeryLazy
  --     if not LazyVim.has 'noice.nvim' then
  --       LazyVim.on_very_lazy(function()
  --         vim.notify = require 'notify'
  --       end)
  --     end
  --   end,
  -- },
  -- {
  --   'folke/noice.nvim',
  --   dependencies = {
  --     'MunifTanjim/nui.nvim',
  --     -- 'rcarriga/nvim-notify',
  --   },
  --   opts = {
  --     cmdline = {
  --       format = {
  --         search_down = {
  --           view = 'cmdline',
  --         },
  --         search_up = {
  --           view = 'cmdline',
  --         },
  --       },
  --     },
  --     lsp = {
  --       override = {
  --         ['vim.lsp.util.convert_input_to_markdown_lines'] = true,
  --         ['vim.lsp.util.stylize_markdown'] = true,
  --         ['cmp.entry.get_documentation'] = true,
  --       },
  --     },
  --     presets = {
  --       bottom_search = true,
  --       command_palette = true,
  --       long_message_to_split = true,
  --       inc_rename = true,
  --       lsp_doc_border = true,
  --     },
  --   },
  --   config = function()
  --     require('noice').setup {
  --       views = {
  --         cmdline_popup = {
  --           position = {
  --             row = 5,
  --             col = '50%',
  --           },
  --           size = {
  --             width = 60,
  --             height = 'auto',
  --           },
  --         },
  --         popupmenu = {
  --           relative = 'editor',
  --           position = {
  --             row = 8,
  --             col = '50%',
  --           },
  --           size = {
  --             width = 60,
  --             height = 10,
  --           },
  --           border = {
  --             style = 'rounded',
  --             padding = { 0, 1 },
  --           },
  --           win_options = {
  --             winhighlight = { Normal = 'Normal', FloatBorder = 'DiagnosticInfo' },
  --           },
  --         },
  --       },
  --     }
  --   end,
  -- },
}
